apiVersion: apps/v1
kind: Deployment
metadata:
  name: credentialapi
  labels:
    app: credentialapi
    group: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credentialapi
  template:
    metadata:
      labels:
        app: credentialapi
        group: backend
    spec:
      containers:
        - name: credentialapi
          image: ilhamgibran/credential-api:0.1.2
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: mongodb-config
          env:
            - name: MONGODB_HOST
              value: "mongodb"
            - name: MONGODB_PORT
              value: "27017"
            - name: TOKEN_KEY
              value: "nodeexpressjwt"
            - name: API_PORT
              value: "8080"