apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  labels:
    group: credentialapp
data:
  MONGO_INITDB_ROOT_USERNAME: ilham
  MONGO_INITDB_ROOT_PASSWORD: inipassword
  MONGO_INITDB_DATABASE: credentialdb